"""
Runs every registered geometry extractor.
"""

from detector.semantic_map import (
    semantic_mapping
)

from .registry import (
    get_registered_features
)


def extract_all_features(
        landmarks,
        enabled=None):

    mapping = semantic_mapping(
        landmarks
    )

    plugins = get_registered_features()

    if enabled is None:

        enabled = plugins.keys()

    features = {}

    for name in enabled:

        if name not in plugins:

            raise ValueError(
                f"Unknown feature plugin: {name}"
            )

        extractor = plugins[name]

        feature_dict = extractor(

            landmarks,

            mapping

        )

        overlap = (
            features.keys()
            &
            feature_dict.keys()
        )

        if overlap:

            raise ValueError(

                f"Duplicate feature names "
                f"generated by '{name}': "
                f"{sorted(overlap)}"

            )

        features.update(
            feature_dict
        )

    return features